[versions]
kotlin = "2.3.0"
agp = "9.0.0-alpha06"
compose = "1.11.0-alpha03+dev3566"
composeIcons = "1.7.3"
activity = "1.12.3"
lifecycle = "2.10.0"
room = "2.8.4"
ksp = "2.3.5"
coroutine = "1.10.2"
koin = "4.1.1"
kotlinSerialization = "1.10.0"
coil = "3.3.0"
zoomable = "2.10.0"
ktlintGradle = "14.0.1"
ktlint = "1.6.0"
workManager = "2.11.1"
androidxTestRules = "1.7.0"
nav3 = "1.0.0-alpha01"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidxRoom = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlingGradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }

[libraries]
androidActivityActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidActivityKtx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidxCoreKtx = { module = "androidx.core:core-ktx", version.require = "1.17.0" }
androidxLifecycleViewModelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidxLifecycleViewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidxLifecycleRuntimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
googleMaterial = { module = "com.google.android.material:material", version.require = "1.13.0" }
androidxNavigationCompose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.require = "2.9.1" }
ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }

# Navigation 3
androidxNavigation3Runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3" }
androidxNavigation3Ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3" }

# WorkManager
androidxWorkRuntime = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }

# ktor
ktorClientCore = { module = "io.ktor:ktor-client-core", version.require = "3.4.0" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.require = "3.4.0" }
ktorClientLogging = { module = "io.ktor:ktor-client-logging", version.require = "3.4.0" }

# Coil
coil3Compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil3NetworkOkHttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

# Kotlin
kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinSerialization" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlinxSerializationProtobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinSerialization" }
kotlinxCoroutineSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutine" }

# DataStore
androidxDatastoreCoreOkio = { module = "androidx.datastore:datastore-core-okio", version.require = "1.2.0" }

# Room
androidxRoomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidxRoomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidxSqliteBundled = { module = "androidx.sqlite:sqlite-bundled", version.require = "2.6.2" }

# Koin
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koinAndroid = { module = "io.insert-koin:koin-android", version.ref = "koin" }

# UI
composeIcons = { module = "br.com.devsrsouza.compose.icons:feather", version.require = "1.1.1" }
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }

# JetBrains Compose (Manual)
composeRuntime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
composeUi = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
composeFoundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
composeMaterial3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose" }
composeMaterial = { module = "org.jetbrains.compose.material:material", version.ref = "compose" }
composeMaterialIconsExtended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "composeIcons" }
composeUiUtil = { module = "org.jetbrains.compose.ui:ui-util", version.ref = "compose" }
composeComponentsResources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }

# Test
androidxTestCoreKtx = { module = "androidx.test:core-ktx", version.require = "1.7.0" }
androidxTestRules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }
androidxTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidxComposeTestJunitAndroid = { module = "androidx.compose.ui:ui-test-junit4-android", version.ref = "compose" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutine" }
